version: "3.9"
services:
  ui:
    build: ./ui
    image: hoss-ui:${VERSION}
    ports:
      - "8080"
    volumes:
      - type: bind
        source: ~/.hoss/ui
        target: /opt/config
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.ui.rule=Host(`${DOMAIN}`) && PathPrefix(`/ui`)"
      - "traefik.http.middlewares.ui-prefix.stripprefix.prefixes=/ui"
      - "traefik.http.middlewares.ui-prefix.stripprefix.forceSlash=false"
      - "traefik.http.routers.ui.middlewares=ui-prefix@docker"
    depends_on:
      - reverse-proxy
      - core
    networks:
      - web
    restart: always
