object_stores:
  - name: default
    description: Default object store
    type: minio
    endpoint: http://localhost
    region: null
    profile: null
    role_arn: null
    notification_arn: null
namespaces:
  - name: default
    description: Default namespace
    bucket: data
    object_store: default
queues:
  - type: amqp
    settings:
      url: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    object_store: default
# - type: sqs
#   settings:
#     queue_name: hoss-api-notifications
#     region: us-east-1
#     profile: hoss-service
#   object_store: s3
server:
  dev: true
  auth_service: http://auth:8080/v1
  elasticsearch_endpoint: http://opensearch:9200
  sync_frequency_minutes: 5
  dataset_delete_delay_minutes: 0
  dataset_delete_period_seconds: 2
