name: Hoss CI Tests

on:
  push:
    branches:
      - main
      - fmwest/tests
  pull_request:
    branches:
      - main

jobs:

  buildAndTest:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install mc
      run: |
        wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -P /home/runner/.local/bin
        chmod +x /home/runner/.local/bin/mc
    - name: Set up the env file with defaults
      run: cd server && make env
    - name: Setup docker network
      run: cd server && make setup
    - name: Build the services
      run: cd server && make build
    - name: Pre-pull minio image to it doesn't build
      run: docker pull minio/minio:RELEASE.2021-11-09T03-21-45Z
    - name: Start up the services for testing
      run: cd server && make config && make up-testing
    - name: Sleep for 30 seconds for everything to come up
      run: |
        docker ps
        echo "waiting 30 seconds to start"
        sleep 10
        docker ps | grep minio
        sleep 10
        docker ps | grep minio
        sleep 10
        docker ps | grep minio
    - name: Run core/config tests
      run: cd server/core && go test ./pkg/config
    - name: Run core/database tests
      run: cd server/core && go test ./pkg/database
    - name: Run core/store tests
      run: cd server/core && go test ./pkg/store
    - name: Run core/worker tests
      run: cd server/core && go test ./pkg/worker
    - name: Run auth tests
      run: |
        cd server/auth
        go install github.com/swaggo/swag/cmd/swag@v1.7.8
        swag init
        go test ./...